safe:        false # GitHub Pages: "true"
auto:        true # Default: "false"
server:      false
server_port: 4000

source:      . # GitHub Pages: <your pages repo>
destination: ./_site # GitHub Pages: <the build dir>
plugins:     ./_plugins
baseurl:     '/jekyll-boilerplate'

future:      true
lsi:         false # GitHub Pages: "false"
pygments:    true # Default: "false". GitHub Pages: "true"
markdown:    maruku
permalink:   date

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style